name: Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build and deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/react-app
            git pull origin main
            
            # Stop old container
            docker stop react-app || true
            docker rm react-app || true
            
            # Build new image
            docker build -t react-app .
            
            # Run new container
            docker run -d -p 80:80 --name react-app react-app
            
            # Clean up old images
            docker image prune -f